name: Blablador Helmholtz
version: 1.0.0
schema: v1
models:
  - name: Blablador
    provider: openai
    model: AUTODETECT
    apiKey: ADD_BLABLADOR_TOKEN_HERE
    apiBase: https://api.helmholtz-blablador.fz-juelich.de/v1

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
