name: Build and Release LaTeX

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        container: texlive/texlive:latest
        steps:
            - uses: actions/checkout@v3

            - run: cd coding_assistants && make
            - name: Upload coding_assistants PDF artifact
              uses: actions/upload-artifact@v4
              with:
                    name: coding_assistants
                    path: coding_assistants/slides.pdf

            - run: cd vibe_coding && make
            - name: Upload vibe_coding PDF artifact
              uses: actions/upload-artifact@v4
              with:
                    name: vibe_coding
                    path: vibe_coding/slides.pdf

    release:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write

        steps:
            - uses: actions/download-artifact@v4
              with:
                    name: coding_assistants
                    path: coding_assistants
            - uses: actions/download-artifact@v4
              with:
                    name: vibe_coding
                    path: vibe_coding
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false
            - name: Upload coding_assistants PDF as Release Asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./coding_assistants/slides.pdf
                asset_name: coding_assistants.pdf
                asset_content_type: application/pdf
            - name: Upload vibe_coding PDF as Release Asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./vibe_coding/slides.pdf
                asset_name: vibe_coding.pdf
                asset_content_type: application/pdf
